components:
  parameters:
    GameId:
      name: gameId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Game identifier

    PurchaseId:
      name: purchaseId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Purchase identifier

    EntitlementToken:
      name: token
      in: path
      required: true
      schema:
        type: string
      description: Entitlement token (signed, expiring)

    Page:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1
      description: Page number for pagination

    Limit:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 50
      description: Items per page
